### ISSUE TITLE
Deletes non-empty directories and fails depending on location.

### ISSUE THREAD

**Issue by cbillhardt** [jasonwhite/ubercopy#2]
@jasonwhite - I am seeing odd behavior that I wanted to get your thoughts on.

Situation:
A directory has files that need to be removed (as per the manifest diff), but also has files that exist in both manifest and manifest.next.  When ubercopy is run, it removes the files that were in manifest, but not manifest.next which is expected.  However, it also deletes the non-empty directory containing these files (and files that exist in both manifest and manifest.next, which I do not believe should be deleted).  Normally, this is not a problem as the files that were in both manifest and manifest.next just get recopied.  However, when running ubercopy to remove/copy files on a particular server, I am getting the following error: Access is denied. (os error 5)  Error: The above destination directories failed to get deleted.

Any ideas as to why?  Is it possible that ubercopy is not geared to different types of servers and the way they handle requests to delete non-empty directories?  Also, should ubercopy be deleting non-empty directories?

Note: Something else I am observing is that directory deletion appears to be rather slow.  For one job, I was observing approximately 35 seconds to delete each directory.  Each directory takes about that time, so it should not be due to large file sizes or amounts of files.  This is over the network so perhaps that is the issue.

**Comment by jasonwhite** [comment]
I think I fixed it with 955db703c4896faabcd86d74301bf74af8980624. It was going too far when climbing the tree when trying to delete empty directories.
